module.exports = {
  tecjonson: /tech/gi,
  xqdl: /x/gi,
  vpp: /vem/gi,
  eoq: /que/gi,
  trabson: /trabalho|trab/gi,
  hiiieiieihhieihieieieeieejehiehehieeheie: /porra/gi,
  chupingole: /chupa e engole/gi,
  cudegualipito: /cu/gi,
  meeeeee: /eita/gi,
  'rx o pai \'-\'': /respeita|rexpeita|rx/gi,
  'ss fon trab': /sim|ss/gi,
  'tru da tru': /verdade/gi,
  'nn todeboa': /não|nao|nn/gi,
};
