module.exports = {
    "tru da tru": /verdade/gi,
    "tecjonson": /tech/gi,
    "xqdl": /x/gi,
    "vpp": /vem/gi,
    "rx o pai '-'": /respeita|rexpeita|rx/gi,
    "eoq": /que/gi,
    "trabson": /trabalho|trab/gi,
    "hiiieiieihhieihieieieeieejehiehehieeheie": /porra/gi,
    "ss fon trab": /sim|ss/gi,
    "nn todeboa": /não|nao|nn/gi,
    "chupingole": /chupa e engole/gi,
    "cudegualipito": /cu/gi,
    "meeeeee": /eita/gi,
}
